#!/bin/bash

OUTPUT_PATH="./bin"
OUTPUT_COMPONENTS="--abi --bin --devdoc"
OPTIMIZATION="--optimize --optimize-runs 200"
ALLOWED_PATHS="--allow-paths ."
OTHER_FLAGS="--overwrite"

EVM_VERSION_ETH=""
EVM_VERSION_QTUM="--evm-version homestead"

SOLC_OPTIONS_ETH="$OUTPUT_COMPONENTS $OPTIMIZATION $EVM_VERSION_ETH -o $OUTPUT_PATH $ALLOWED_PATHS $OTHER_FLAGS"
SOLC_OPTIONS_QTUM="$OUTPUT_COMPONENTS $OPTIMIZATION $EVM_VERSION_QTUM -o $OUTPUT_PATH $ALLOWED_PATHS $OTHER_FLAGS"

solc $SOLC_OPTIONS_ETH contracts/common/ERC20Token.sol
solc $SOLC_OPTIONS_ETH contracts/L2DexEthereum.sol

solc $SOLC_OPTIONS_QTUM contracts/common/QRC20Token.sol
solc $SOLC_OPTIONS_QTUM contracts/L2DexQTUM.sol